### ISSUE TITLE
Upgrade to Flink 1.16

### ISSUE THREAD

**Issue by sandeep540** [aiven/sql-cli-for-apache-flink-docker#22]
# What is currently missing?

Upgrade to Flink 1.16

# How could this be improved?

new features on 1.16

# Is this a feature you would work on yourself? - I can, but need access to dockerfile for sql-client

* [ x] I plan to open a pull request for this feature

**Comment by ftisiot** [comment]
Hi! 

Thanks for the issue! You find the dockerfile under sql-cli-for-apache-flink-docker)/sql-client/
